# AdvancedSpawners
# Made by GC

# Version: 3.6.13
# Release date: 2022/02/13

# ** Commands and permissions
# /advancedspawners - Main command; Permission: 'advancedspawners.help'

# Some configurable settings are explained, others should be self-explanatory.
# Join https://advancedplugins.net/discord for support with configuration.

# General Settings
settings:
  # Available languages list: https://as.advancedplugins.net/languages
  # You can edit any language file in /AdvancedSpawners/lang folder
  language: 'en'

  # Spawner Item Settings
  spawnersDisplay:
    # Should spawner item be glowing?
    glowing: true

# Settings for Spawner Stacking
spawnerConfiguration:
  # Is spawner stacking enabled
  # Explanation: Spawner Stacking is combining multiple spawners into one block
  # It greatly increases server performance and reduces number of blocks players must place
  enabled: true

  # Placement Permissions
  # Should permissions for each spawner to place be enabled?
  # Permission is 'as.place.<mob name>' - works with Custom & Vanilla mobs
  placementPermissions: false

  # Limit of stacked spawners per one spawner block
  # Set to 0 for unlimited amount
  spawnerStackLimit: 0

  # Radius in which placed spawners will be combined
  # If set to 0, player will need to right-click spawner block for stacking
  combiningRadius: 3

  # Should spawners have a random chance to drop spawners when exploded?
  # Set 100 to always drop, 0 to never drop.
  dropFromExplosionChance: 10

  # Placing / Breaking messages
  stackInteraction:
    # Message types for placing & breaking spawners
    # Change to 'NONE' to disable
    # - CHAT
    # - ACTIONBAR
    # - NONE
    messageType: CHAT

    # Changing Spawner Type with Monster Eggs
    # Permission: advancedspawners.changeTypeWithEgg
    changeSpawnerWithMonsterEgg: false

  # Hologram Configuration
  holograms:
    # Should static holograms on top of spawners be enabled?
    # Holograms display amount of mobs stacked in the spawner, e.g. "Zombie Spawner (x1)"
    enabled: true

  # Spawning amount per Spawner in stack
  # Formats:
  # - '<min>-<max>', e.g.: '1-3', random number of mobs between 1 and 3 to be spawned per spawner
  # - '<amount>' e.g.: '1', 1 mob will be spawned per spawner
  # Whatever random number is used, it will be multiplied by number of spawners
  spawningAmount: '1-3'

  # Settings for mob stacking
  mobSettings:
    # Should mobs stack?
    # Enabling this will yield huge performance increase
    # Recommended to leave as 'true'
    stackMobs: true

    # In what radius should mobs stack?
    # Maximum radius size: 16
    stackRadius: 16

    # Minimum mobs of same type in combining radius for mobs to start stacking
    # Set to -1 to disable
    minimumMobs: -1

    # Should name be shown without amount when stacked mob count is just 1?
    showStackedNameWithoutAmount: true

    # Kill whole stack? If set to false, mobs will be killed one by one
    killWholeStack: false

    # Maximum Stack size for mobs
    # Set to -1 to disable
    maximumStackSize: -1

    # Stacking Blacklist
    # Mobs that shouldn't stack
    stackingBlacklist:
      - 'WITHER'
      - 'ENDER_DRAGON'
      - 'PARROT'
      - 'WOLF'
      - 'CAT'

    # Stacking World blacklist
    # Worlds, in which mobs will not be stacked
    stackingWorldsBlacklist:
      - 'EXAMPLE_WORLD'
      - 'ANOTHER_EXAMPLE_WORLD'

    # For what spawning reasons should not stack mobs?
    # This works for vanilla & custom mobs
    # Spawn Reasons: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/entity/CreatureSpawnEvent.SpawnReason.html
    stackReasonsBlacklist:
      - CUSTOM #Disables stacking from plugins spawning mobs
      - BEEHIVE

  # Spawner Breaking Configuration
  breaking:
    # Should all spawners break at once spawner block is broken?
    breakAll: false

    # Is silktouch enabled for spawners?
    # Players require 'advancedspawners.silktouch' permission to use this
    # Use chances for dropping broken spawners: 'advancedspawners.silktouch.<percentage amount>' (1-100)
    # If player doesn't have the chance permission, it will drop 100% of the time
    spawnersSilkTouch: true

    # No Silktouch warning
    # Should a player with silktouch permission and without the enchantment on item
    # have the spawner breaking cancelled?
    noSilktouch:
      warning: true

    # If silktouch is enabled for spawners, what level of silk touch
    # is required to mine spawners?
    spawnerSilkTouchLevel: 1

    # Should broken spawners teleport to inventory?
    teleportOnBreak: false

    # Should natural spawners drop when silktouched?
    dropNatural: true

# Configuration for Random Mob Spawning
randomSpawning:
  # Is Random Spawning enabled?
  enabled: true

  # In what radius of player should mobs spawn?
  # This respect all limitations of server (i.e. spawning range set)
  playerRadius: 40

  # What is the chance custom mob will spawn?
  # The higher the chance, the more will spawn
  # Setting to 100% will not make all mobs custom, only all attempts custom mobs (highest count of mobs)
  spawnChance: 50

  # How many custom mobs at total can be on the server?
  # This limit is only for random spawned custom mobs
  randomMobLimit: 50

  # Random Spawn-able custom mobs list
  mobsAllowedToRandomSpawn:
    - 'Gorilla'
    - 'Monkey'
    - 'Dragon'
    - 'Tiger'
    - 'Turtle'

  # Worlds list for random spawning
  # In what worlds should random custom mobs spawn
  worldList:
    - 'world'

# General mob settings, may not apply to custom mobs
# Changes behaviours throughout the server
generalMobSettings:

  # Should mobs have AI?
  # If set to false, mobs will become 'dumb' and wont move or be aggressive
  mobAI: true

  # How many max hits are allowed to be done on mobs in 1 second?
  hitCount: 8

  # Should hostile mobs burn in sunlight?
  hostileBurn: true

  # Should mobs drop items when dying due to fall damage
  fallDamageDrops: true

  # Should whole mob stack die on fall damage?
  # This is useful for fall damage based grinders
  fallDamageDieAll: true

  # Should mobs drop exp when they get killed by fall damage?
  fallDamageExp: true

  # Disable all functionality with vanilla spawners / mobs?
  disableAllVanillaFunctions: false

  # Should mob knockback be enabled?
  mobKnockbackEnabled: true
